version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=t2gcs
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
    driver: local
